### ISSUE TITLE
modulo correios mundi

### ISSUE THREAD

**Issue by wubuyun** [bubbstore/correios#4]
pretendi coloca correios mundi?

## Descrição detalhada

Forneça uma descrição detalhada da alteração ou adição que você está propondo.

Deixe claro se o problema é um bug, um aprimoramento ou apenas uma pergunta.

## Contexto

Por que essa mudança é importante para você? Como você usaria isso?

Como pode beneficiar outros usuários?

## Possível implementação

Não é obrigatório, mas sugere uma idéia para implementar adição ou mudança.

## Seu ambiente

Inclua detalhes relevantes sobre o ambiente em que você identificou o bug e como reproduzi-lo.

* Vesão usada (e.g. PHP 5.6, HHVM 3):
* Sistema operacional e versão (e.g. Ubuntu 16.04, Windows 7):
* ...
* ...

**Comment by lucascolette** [comment]
Pode ser mais específico?

**Comment by wubuyun** [comment]
calcular o frete usando o método internacional dos Correios
https://github.com/luizwbr/SedexMundiVirtueMart

2018年4月18日 上午7:47，Lucas Colette <notifications@github.com>写道：

Pode ser mais específico?

**Comment by lucascolette** [comment]
Sem planos para isso, por enquanto.

Mas fique a vontade para enviar um Pull Request com essa feature.

Abs.

**Comment by wubuyun** [comment]
Ok, obrigado

2018年4月18日 上午10:49，Lucas Colette <notifications@github.com>写道：

Sem planos para isso, por enquanto.

Mas fique a vontade para enviar um Pull Request com essa feature.

Abs.
