### ISSUE TITLE
Dúvidas ou Sugestões(2018)

### ISSUE THREAD

**Issue by PauloBoaventura** [bubbstore/correios#5]
## Descrição detalhada
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE. (O que neste notamos que o upgrade é notavel).

##### Forneça uma descrição detalhada da alteração ou adição que você está propondo.

Deixe claro se o problema é um bug, um aprimoramento ou apenas uma pergunta.

## Contexto

Por que essa mudança é importante para você? Como você usaria isso?

Como pode beneficiar outros usuários?

## Possível implementação

Não é obrigatório, mas sugere uma idéia para implementar adição ou mudança.

## Seu ambiente

Inclua detalhes relevantes sobre o ambiente em que você identificou o bug e como reproduzi-lo.

* Vesão usada (e.g. PHP 5.6, HHVM 3):
* Sistema operacional e versão (e.g. Ubuntu 16.04, Windows 7):
* ...
* ...

VERSÃO: php 5,6, 7.0
centos 7
plesk
magento (se possivel)

**Comment by lucascolette** [comment]
@PauloBoaventura a lib tem compatibilidade com o PHP 5.6 até 7.2.

Fique a vontade para enviar um Pull Requests com o UPGRADE que menciona, pois não ficou claro para mim.

**Comment by PauloBoaventura** [comment]
A mesma resposta em: https://github.com/bubbwebstudio/bubb-correios/issues/1#issuecomment-386874236

**Comment by lucascolette** [comment]
@PauloBoaventura o repositório que citou foi descontinuado. Você mesmo pode implementar essa lib no magento. Não tenho intenção de fazer isso.

Abraços.
