### ISSUE TITLE
Rastreio: Array faltando status no traking quando a data e hora é igual em dois status

### ISSUE THREAD

**Issue by rafaelxavierborges** [bubbstore/correios#6]
O array do status mais abaixo no html é sobrescrito:

Exemplo:

08/05/2018 10:51 | Objeto entregue ao destinatário
08/05/2018 10:51 | Objeto aguardando retirada no endereço indicado

Somente esse status mais abaixo é retornado na response.

O problema se encontra aqui no arquivo -> correios/src/bubbstore/Correios/CorreiosTracking.php (linha 52):

$arr[$date] = [
             'date' => $date,
             'status' => $status,
];

O identificador é a data e hora e por isso acontece este problema.
Poderia nos ajudar?

**Comment by lucascolette** [comment]
@rafaelxavierborges já testou se mudando o índice para o status, por exemplo, funciona?

**Comment by rafaelxavierborges** [comment]
Mudei o indice para um contador $i. Funcionou. Quer que te envie o arquivo?

**Comment by rafaelxavierborges** [comment]
[CorreiosTracking.zip](https://github.com/bubbstore/correios/files/2045195/CorreiosTracking.zip)

**Comment by lucascolette** [comment]
@rafaelxavierborges envie um Pull Request, por favor.

**Comment by rafaelxavierborges** [comment]
Vou mandar.
